##
# This is a utility type, include it for a configuration
# if a jump marker navigation should be shown on the page.
##
'CodeQ.JumpMarkers:Mixin.PageConfiguration':
  abstract: true
  properties:
    showJumpMarkersMenu:
      type: boolean
      defaultValue: false
      ui:
        label: i18n
        reloadIfChanged: true
        inspector:
          group: document
          position: 1000300
