'CodeQ.JumpMarkers:Mixin.PageConfiguration':
  abstract: true
  properties:
    jumpMarkersEnabled:
      type: boolean
      defaultValue: false
      ui:
        label: i18n
        reloadIfChanged: true
        inspector:
          group: document
          position: 1000300
